### ISSUE TITLE
fix: Unexpected input(s) 'flutter-version'

### ISSUE THREAD

**Issue by must-ismail** [shorebirdtech/shorebird#1247]
**Description**

Github action doesn't accept `flutter-version` parameter.

**Expected Behavior**

Accept `flutter-version` parameter.

**Screenshots**

![image](https://github.com/shorebirdtech/shorebird/assets/111011839/bbc9d60d-35b2-4e11-a272-d1d276aed22a)

**Additional Context**

`shorebird flutter versions use` can be used after setup Shorebird until issue is resolved.

**Comment by felangel** [comment]
Hi 👋 
Can you share a minimal reproduction sample (e.g your current GitHub workflow)? Thanks!

**Comment by mshahjahan-mufin** [comment]
@felangel Here is the sample:


```
   - name: 🐦 Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v0
        with:
          flutter-version: 3.13.0

  - name: 🎯 Flutter Version
        run: |
          shorebird flutter versions use 3.13.0
          shorebird flutter versions use 3.13.0
 
 - name: 🚀 Shorebird Patch
        run: shorebird patch android --force 
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
```
