### ISSUE TITLE
fix:  "Runner.app" requires a provisioning profile with the Associated Domains, HealthKit, Near Field Communication Tag Reading, and Push Notifications features.

### ISSUE THREAD

**Issue by fitterfly-parth** [shorebirdtech/shorebird#1248]
shorebird release ios-alpha --flavor stage

After running this command get the below error.

✗ Failed to build IPA (304.5s)
    "Runner.app" requires a provisioning profile with the Associated Domains, HealthKit, Near Field Communication Tag Reading, and Push Notifications features.
<img width="1365" alt="Screenshot 2023-09-11 at 12 03 07 PM" src="https://github.com/shorebirdtech/shorebird/assets/104829044/f8350498-8935-4052-920e-cd040b9aa9ea">

**Comment by eseidel** [comment]
We'd love to learn more from you about how you normally build with Flutter?  Sounds like the way we're calling `flutter build` from within Shorebird must be missing something about your normal provisioning setup?  Do you typically build from XCode?  Do you ever build with `flutter build ios --release`?  If so, what's the command you use?  Thanks!

You can also reach us on discord: https://discord.gg/shorebird.

**Comment by fitterfly-parth** [comment]
We usually generate a build from xCode using Product -> Archive. But when I tried to generate a build using the shorebird command it threw the above error. So I try with flutter's 'flutter build ios --release --flavor live' command and it's working fine for me.

<img width="958" alt="Screenshot 2023-09-12 at 10 45 40 AM" src="https://github.com/shorebirdtech/shorebird/assets/104829044/6c5d93fb-ec41-46cd-ab30-33489d2ef5b3">

**Comment by fitterfly-parth** [comment]
We have info.plist and Entitlement file so is there any issue with this file?

<img width="1170" alt="Screenshot 2023-09-12 at 10 47 01 AM" src="https://github.com/shorebirdtech/shorebird/assets/104829044/8265c069-2956-4b6b-b7a3-fc04fdad5d11">

**Comment by bryanoltman** [comment]
I'm trying to reproduce the issue locally and have been unsuccessful so far. The closest I think I've gotten is an error message saying "Provisioning profile "iOS Test App Store Distribution" doesn't support the HealthKit", which is similar to what you were seeing but slightly different, and I see the same issue when running `flutter build ios --release`.

It looks like your entitlements are all correct. Is Is "automatically manage signing" enabled for your project? Can you show me what the "signing and capabilities" pane in Xcode looks like for this project?

**Comment by bryanoltman** [comment]
Also, I'd be curious to see what output `flutter build ipa --release` shows you.

**Comment by fitterfly-parth** [comment]
No, there is no auto-managing certificate we do it manually 
<img width="898" alt="Screenshot 2023-09-13 at 10 22 26 AM" src="https://github.com/shorebirdtech/shorebird/assets/104829044/572f3650-208b-49d9-91d6-4ddf66600936">

**Comment by fitterfly-parth** [comment]
Result of flutter build ipa --release

<img width="1389" alt="Screenshot 2023-09-13 at 10 25 00 AM" src="https://github.com/shorebirdtech/shorebird/assets/104829044/822fbf18-1fa8-4b40-90d6-b7c7b5d2b61c">

**Comment by fitterfly-parth** [comment]
And please also guide me on how to upload this ipa on AppStore.

**Comment by bryanoltman** [comment]
This has been fixed with the addition of the `--no-codesign` flag to the `shorebird release ios-alpha` command. This flag generates an unsigned .xcarchive that can be distributed through Xcode, and should play better with CI pipelines.

See our [iOS releasing guide](https://docs.shorebird.dev/guides/release/ios) for more info.

**Comment by powilliam** [comment]
I know this issue was closed but this also can be addressed using the `--export-options-plist` option during `release` or `patch` commands. You can manually create this plist file or, if using Codemagic, their code signing processes will normally create it for you. Just check on the logs to see where it was stored. I do have something like this on my CI

```yml
definitions:
  - &setup-ios-signing
    name: Setup iOS code signing
    script: |
      keychain initialize
      app-store-connect fetch-signing-files "$(xcode-project detect-bundle-id)" \
            --type IOS_APP_STORE \
            --create
      keychain add-certificates
      xcode-project use-profiles

workflows:
  xpto-workflow:
    scripts:
      - *setup-ios-signing
      - name: Release iOS
        script: |
         shorebird release ios-alpha -- \
            --export-options-plist /Users/builder/export_options.plist
```
