### ISSUE TITLE
fix: CLI does not detect misconfigured project

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#1265]
**Description**

As a user, if I have forgotten to add `shorebird.yaml` to the assets section of the `pubspec.yaml` I expect Shorebird should detect that and prevent me from releasing.

**Steps To Reproduce**

```yaml
name: new_app
description: none
version: 1.0.0+1
 
environment:
  sdk: '>=3.1.1 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter
  shorebird_code_push: ^1.1.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
 
flutter:
 
```

Shorebird creates a release with the above `pubspec.yaml`

**Expected Behavior**

Shorebird should prevent creating a bad release. Reported by a tester via Discord.
