### ISSUE TITLE
Explain how to pass allowProvisioningUpdates

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1598]
Question from a customer on Discord:

```
We attempted to use Shorebird for an iOS release in an Azure Pipeline with the following command:
shorebird release ios-alpha --flavor dev -- --export-options-plist=./ExportOptions.plist

In the export options, we configured automatic signing. However, we encountered the following error:
Error (Xcode): No profiles for 'xxx.xxx.app.dev' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'xxx.xxx.app.dev' Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. 

Subsequently, we modified it to manual signing and retried the release command in the pipeline. Unfortunately, we are still encountering the same error. Is there any way to pass allowProvisioningUpdates in the Shorebird iOS release command? or is there any other options?
```

**Comment by eseidel** [comment]
`shorebird` accepts any option `flutter` can, it passes them separately after a `--`

So for example:

`shorebird release ios-alpha -- --foo` would pass --foo down to the underlying `flutter build` command.

**Comment by sabarinath-kv** [comment]
In our old iOS pipeline, we used Xcode@5 from azure for archiving @eseidel 
    
    
 ```
- task: Xcode@5
            displayName: "Export $(build_env) ipa"
            inputs:
              actions: "archive"
              configuration: "Release-$(build_env)"
              xcWorkspacePath: "$(projectDirectory)/ios/Runner.xcworkspace"
              scheme: "$(build_env)"
              xcodeVersion: "specifyPath"
              xcodeDeveloperDir: "/Applications/Xcode_14.2.app"
              packageApp: true
              archivePath: "$(projectDirectory)/ios/build/Runner.xcarchive"
              exportPath: "$(projectDirectory)/ios/build"
              signingOption: "manual"
              signingIdentity: "$(APPLE_CERTIFICATE_SIGNING_IDENTITY)"
              provisioningProfileUuid: "$(APPLE_PROV_PROFILE_UUID)"
              args: "-verbose"
              workingDirectory: "$(projectDirectory)/ios"
              ```
