### ISSUE TITLE
fix: `patch ios` reports native changes if patch is run in a different folder than release

### ISSUE THREAD

**Issue by nikhiln** [shorebirdtech/shorebird#1780]
App ID: f05e5303-baa0-4877-ada8-5c52f162b1eb

**Description**

Patches not working when having the flavour support using [`flutter_flavorizr`](https://pub.dev/packages/flutter_flavorizr). Try to create patch specifically for ios and it always complains with warning:

**_`Your app contains native changes, which cannot be applied with a patch.`_**

**Steps To Reproduce**

1. Create new flutter app - with single screen (with "Hello world" text)
2. Add flavour support using flutter_flavorizr
3. Create a shorebird release from your local and published it
4. Clone the same setup or try to run using CI/CD and create a new patch for ios (you might simply want to change displayed text)
5. It always complain about native changes even though nothing is changed really.
6. However, if you try to create patch locally (on the original folder where you created the app), it's working.

**Expected Behavior**

It should create the patch correctly without warning when the code gets cloned and having no native changes really.

**Additional Context**
None

**Comment by eseidel** [comment]
It looks like flutter_falvorizor has a lot of options.  Would you be willing to share your config?

**Comment by nikhiln** [comment]
Sure, here's the config you can put into pubspec:

```
flavorizr:
  flavors:
    dev:
      app:
        name: "Dev App"
      android:
        applicationId: "app.hello.dev"
      ios:
        bundleId: "app.hello.dev"
    stage:
      app:
        name: "Stage App"
      android:
        applicationId: "app.hello.stage"
      ios:
        bundleId: "app.hello.stage"
    prod:
      app:
        name: "Prod App"
      android:
        applicationId: "app.hello"
      ios:
        bundleId: "app.hello"
```
