### ISSUE TITLE
feat: add `--flutter-version` to `shorebird patch` command

### ISSUE THREAD

**Issue by must-ismail** [shorebirdtech/shorebird#1807]
**Description**

You removed the `shorebird flutter versions use` command, now we have to use `--flutter-version`. However, this does not seem to be applicable in the patch command. Therefore, in the pipeline, the patch is created with the latest Flutter version, then it loads the correct version and creates it again. Waste of time and money.

<img width="691" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/111011839/b6a743c0-d32b-4d3b-b5da-abbe617b8c17">

**Requirements**

- [ ] Add `--flutter-version` to `shorebird patch` command

**Additional Context**

Also, the [Github documentation](https://docs.shorebird.dev/ci/github) is outdated and still references the old command for the Flutter version. The old command started giving errors in pipeline.

**Thank you for your attention!**

**Comment by bryanoltman** [comment]
Patch will automatically use the same Flutter version that was used to create the release. There is not a way to override this. You can provide the release version that the patch is targeting using the `--release-version` option (ex: `shorebird patch android --release-version=1.2.3+4`) to skip the release version detection step.

**Comment by bryanoltman** [comment]
And thank you for letting us know about the docs. Updating those now! 🙂

**Comment by must-ismail** [comment]
@bryanoltman Thank you for responses.

I hope this helps someone in the future. It takes the version from pubspec.yaml and sends it to Shorebird in workflow. 

```
      - name: 🧩 App version
        id: yq
        uses: mikefarah/yq@master
        with:
          cmd: yq -r '.version' 'pubspec.yaml'

      - name: 🚀 Shorebird Patch
        run: shorebird patch android --release-version ${{ steps.yq.outputs.result }}
```
