### ISSUE TITLE
fix: shorebird release ios does not recognize the profiles in Codemagic.

### ISSUE THREAD

**Issue by Segatti** [shorebirdtech/shorebird#1889]
App ID: a46deb1e-6f5b-447a-8f42-da816751bc33

**Description**

**I'm with the following shorebird configuration file:**

```
workflows:
  ios-release:
    name: iOS Release
    instance_type: mac_mini_m1
    max_build_duration: 60
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: --.---.------------
      groups:
        - app_aluno
        - shorebird
      vars:
        APP_STORE_APPLE_ID: -------------
      flutter: 3.16.9
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create files secrets
        script: |
          #!/bin/sh
          echo $ENV_ALUNO | base64 --decode > $CM_BUILD_DIR/.env
          echo $FIREBASE_IOS_ALUNO | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
          echo $FIREBASE_ANDROID_ALUNO | base64 --decode > $CM_BUILD_DIR/android/app/google-services.json
      - name: 🐦 Setup Shorebird
        script: |
          # Install Shorebird
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash

          # Add Shorebird to PATH
          echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Clear cache Flutter
        script: |
          flutter pub cache clean -f
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
        ignore_failure: false
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: false
      - name: 🚀 Shorebird Release
        script: shorebird release ios
      # - name: Flutter build ipa and automatic versioning
      #   script: |
      #     flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - "email"
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
      slack:
        channel: "#opd-devops-notification"
        notify_on_build_start: false
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          - "Testers Interno"
        submit_to_app_store: false
```

**And I'm receiving the following error in codemagic:**

```
⠋ Fetching apps...
✓ Fetching apps (0.3s)
⠋ Building release with Flutter 3.19.5 (25bc2b57a1)...
✗ Failed to build (204.5s)
    No Accounts
    No profiles for '_.__.___.TimerLiveActivity' were found
    No profiles for '_.__.___.HomeWidget' were found
    No profiles for '_.__.___' were found

If you aren't sure why this command failed, re-run with the --verbose flag to see more information.


Build failed :|
Step 12 script `🚀 Shorebird Release` exited with status code 70
```
**This only happens with iOS on shorebird, if I generate a normal version, this error does not occur.**

**Steps To Reproduce**

1. run 'shorebird release ios' in codemagic
2. See error

**Expected Behavior**

I hope to be able to compile successfully.

**Additional Context**

I use app extensions for Home Widget and Live Activity.
