### ISSUE TITLE
fix: patch not being applied on iOS - using wrong app ID

### ISSUE THREAD

**Issue by adamkoch** [shorebirdtech/shorebird#2004]
App ID: 0a4358e2-d269-4b1e-990e-d6a7009fe5f0

**Description**

On Android, everything worked fine. On iOS, I didn't see the patch coming through, following the [troubleshooting guide](https://docs.shorebird.dev/troubleshooting#the-patch-was-created-for-a-different-release-version-than-the-one-running-on-your-deviceemulator), I checked the iOS logs and sure enough, it's not finding the patch because it's checking the wrong app_id:

```
[INFO:shorebird.cc(173)] Shorebird updater: no active patch.
Sending patch check request: PatchCheckRequest { app_id: "0a4358e2-d269-4b1e-990e-d6a7009fe5f0", channel: "stable", release_version: "1.2.29+1229", patch_number: None, platform: "ios", arch: "aarch64" }
```

My production app_id is `0f7a6dc6-bccc-4343-a208-3a63a9cb8b3f` and it's checking my beta app id (`0f7a6dc6-bccc-4343-a208-3a63a9cb8b3f`).

However, when using shorebird CLI, it did choose the prod track fine for the releases and the patches. There is nothing in beta or dev.

Looking at my `shorebird.yaml`:
```
app_id: 0a4358e2-d269-4b1e-990e-d6a7009fe5f0
flavors:
  beta: 0a4358e2-d269-4b1e-990e-d6a7009fe5f0
  dev: ae343dd9-879d-442b-a9ba-da0e75d36654
  prod: 0f7a6dc6-bccc-4343-a208-3a63a9cb8b3f
```

It seems it chose beta as the main app_id. Can I flip the main app_id over to the prod one to fix this?

Thanks!
