### ISSUE TITLE
fix: IOS builds successfully but I don't see the release on Shorebird console. 

### ISSUE THREAD

**Issue by Fateh-Hamdani** [shorebirdtech/shorebird#2291]
App ID: d5925329-51d9-4d3c-b4de-907468e22ce6

I am building my app using Codemagic
Here is my yaml file 

```
definitions:
      scripts:
      - &setupShorebird
        name: Setup Shorebird
        script: |
          # Install Shorebird
          curl --proto "=https" --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash

          # Add Shorebird to PATH
          echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV
      - &setupCodeSigningIdentities
        name: Set up code signing settings for Xcode project
        script: |
          xcode-project use-profiles

      - &installingDependencies
        name: Installing dependencies
        script: |
            flutter packages pub get
      
workflows:
  Developement-release-workflow:
    name: Developement Release Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: Codemagic
    environment:
      android_signing:
        - keystore_reference
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: ___.________.__
      groups:
        - shorebird_credentials
        - firebase_credentials
        
      vars:
        TYPE: "release" # Can be "patch" or "release"
        PACKAGE_NAME: "___.________.__"
        GOOGLE_PLAY_TRACK: "alpha"
        APP_ID: 6450890442
      flutter: 3.22.1 
      java: 17
      xcode: latest
      cocoapods: default
    scripts:
    
      - *installingDependencies
      - *setupCodeSigningIdentities 
      - *setupShorebird
      - name: Building IOS
        script: shorebird release ios -t lib/main_dev.dart --flavor dev -n -- --export-options-plist=/Users/builder/export_options.plist --verbose
      - name: Building Android
        script: shorebird release android --target ./lib/main_dev.dart --flavor dev --artifact apk 

    artifacts:
      - /Users/builder/clone/build/app/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
 
```
the build was completed with success and here is the Output

```
⠋ Fetching apps...
✓ Fetching apps (0.3s)
⠋ Building ipa with Flutter 3.22.2 (7cab65034f)...
✓ Building ipa with Flutter 3.22.2 (7cab65034f) (258.3s)
⠋ Fetching releases...
✓ Fetching releases (96ms)
No issues detected.
The server may enforce additional checks.
```

note that there are no errors but I still see no releases in the Shorebird console as a result I can't run patches.
it works fine for Android but not for IOS
