### ISSUE TITLE
fix: wrong app id being used on iOS with flavors

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#2375]
App ID: 7e87c4f4-78a9-4dc8-bdc9-0953e68607cb

**Description**

The customer (https://discord.com/channels/1030243211995791380/1265104447575429144) has an app with several flavors and is using the following commands to release and patch:

```
shorebird release ios --flutter-version $FLUTTER_VERSION_CODE --flavor staging --target lib/main_staging.dart --no-codesign -- --build-number=$BITRISE_BUILD_NUMBER
```

```
shorebird patch ios --target lib/main_staging.dart --flavor staging --release-version 1.1.0+2764 --no-codesign
```

`$FLUTTER_VERSION_CODE` is `3.22.2`

The `shorebird.yaml` being included in the generated IPA is

```yaml
# This file is used to configure the Shorebird updater used by your app.
# Learn more at https://docs.shorebird.dev
# This file should be checked into version control.

# This is the unique identifier assigned to your app.
# Your app_id is not a secret and is just used to identify your app
# when requesting patches from Shorebird's servers.
app_id: 339dbee2-12bf-41f1-b235-1b9817886889
flavors:
  development: 339dbee2-12bf-41f1-b235-1b9817886889
  production: 0f468324-95c5-4fe2-a600-d997a80ef335
  staging: 7e87c4f4-78a9-4dc8-bdc9-0953e68607cb
  OneSignalNotificationServiceExtension: efb6dd22-9f3f-4217-8f33-269acb5ac7d4

# auto_update controls if Shorebird should automatically update in the background on launch.
# If auto_update: false, you will need to use package:shorebird_code_push to trigger updates.
# https://pub.dev/packages/shorebird_code_push
# Uncomment the following line to disable automatic updates.
# auto_update: false
```

But the `shorebird.yaml` that _should_ be included is:

```yaml
app_id: 7e87c4f4-78a9-4dc8-bdc9-0953e68607cb
```

**Comment by bryanoltman** [comment]
Running a very similar command:

```
shorebird release ios --flutter-version 3.22.2 --flavor stable --no-codesign -- --build-num
ber=1234
```

on our flavors sample (https://github.com/shorebirdtech/samples/tree/main/flavors) results in the following shorebird.yaml being included in the .xcarchive (no ipa is generated due to the `--no-codesign` flag):

```yaml
app_id: 7a4eb02b-90c0-460b-9fde-99130d7f38a2
```

This is expected. The full `shorebird.yaml` is

```yaml
# This file is used to configure the Shorebird updater used by your app.
# Learn more at https://docs.shorebird.dev
# This file does not contain any sensitive information and should be checked into version control.

# Your app_id is the unique identifier assigned to your app.
# It is used to identify your app when requesting patches from Shorebird's servers.
# It is not a secret and can be shared publicly.
app_id: ee49835a-745b-4a33-95ab-ac964a39cfa9
flavors:
  internal: ee49835a-745b-4a33-95ab-ac964a39cfa9
  stable: 7a4eb02b-90c0-460b-9fde-99130d7f38a2

# auto_update controls if Shorebird should automatically update in the background on launch.
# If auto_update: false, you will need to use package:shorebird_code_push to trigger updates.
# https://pub.dev/packages/shorebird_code_push
# Uncomment the following line to disable automatic updates.
# auto_update: false
```
