### ISSUE TITLE
fix: `shorebird release` fails if Android has flavors but iOS does not

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#2411]
https://discord.com/channels/1030243211995791380/1271537382579114087/1271537382579114087

```
shorebird detected a dev and prod flavour because I set these up on Android. It's not as trivial to setup flavours on iOS so I haven't done so yet. shorebird release ios fails if I specify a flavour because it doesn't exist. Is there a workaround for this?
```

**Comment by felangel** [comment]
Can you share the contents of your `shorebird.yaml`?

**Comment by eseidel** [comment]
@felangel the original commenter is not on this bug, I don't think.  It came in via Discord.

**Comment by britannio** [comment]
```yaml
app_id: d1a66907-3c2e-471a-b742-f5f565afc7e4
flavors:
  dev: e9a62abc-cc87-49a3-8eb7-be64a0e82d80
  prod: 96959501-9df7-404a-9819-727f8ba7a6a4
  ```
