### ISSUE TITLE
fix: patches for windows keep failing in ci/cd

### ISSUE THREAD

**Issue by Bahrom2101** [shorebirdtech/shorebird#2794]
I released for windows in ci and everything was good. But if try to build patch everytime it fails. 

i tried both 
```      
- name: 🚀 Use Shorebird
  run: shorebird patch --platforms=windows --release-version=2.6.2+134
```
and
```     
- name: 🚀 Shorebird Patch
  uses: shorebirdtech/shorebird-patch@v0
  with:
    platform: windows
``` 
in ci/cd script

<img width="1123" alt="Image" src="https://github.com/user-attachments/assets/fe456ea0-264a-4a15-8bf6-bced5ec9cca5" />

**Comment by bryanoltman** [comment]
Thank you for the report! To make sure I follow, you created the release and the patch in the same CI? Do you track your pubspec.lock file in source control?

**Comment by Bahrom2101** [comment]
yes pubspec.lock is not in gitignore. but what do you mean by "the same CI"? I have 2 .yml files, one for releases and one for patches. am I doing this correct?

<img width="789" alt="Image" src="https://github.com/user-attachments/assets/d7364001-a5db-4cac-aa74-bbd90e40ea67" />
<img width="785" alt="Image" src="https://github.com/user-attachments/assets/3170e892-328b-47da-a675-19fab4b1e4f7" />

**Comment by bryanoltman** [comment]
By "same CI", I meant "(roughly) the same environment", which it looks like you're using. Can you share your app id?

**Comment by bryanoltman** [comment]
I think I found it: `ae500169-94a4-4db1-9c99-4cd14b2414bd`

Can you share your pubspec.yaml? I'd like to try to reproduce this on my side so I can fix.

**Comment by Bahrom2101** [comment]
> I think I found it: `ae500169-94a4-4db1-9c99-4cd14b2414bd`
> 
> Can you share your pubspec.yaml? I'd like to try to reproduce this on my side so I can fix.

Sure thing. 

```
dependencies:
  flutter:
    sdk: flutter
  international_phone_numbers:
    path: local_packages/international_phone_numbers
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.1
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  formz: ^0.7.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  dio: ^5.6.0
  retrofit: ^4.2.0
  either_dart: ^1.0.0
  flash: ^3.1.1
  intl: ^0.19.0
  package_info_plus: ^8.0.2
  flutter_spinkit: ^5.2.1
  percent_indicator: ^4.2.3
  dotted_border: ^2.1.0
  flutter_typeahead: ^5.2.0
  shimmer: ^3.0.0
  barcode_widget: ^2.0.4
  syncfusion_flutter_datepicker: ^27.2.2
  web_socket_channel: ^3.0.1
  font_awesome_flutter: ^10.7.0
  animated_toggle_switch: ^0.8.3
  pin_code_fields: ^8.0.1
  uuid: ^4.4.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4
  go_router: ^14.2.3
  device_info_plus: ^10.1.2
  logger: ^2.4.0
  get_it: ^7.7.0
  syncfusion_localizations: ^27.2.2
  easy_localization: ^3.0.7
  printing: ^5.13.4
  pdf: ^3.11.1
  flutter_switch: ^0.3.2
  syncfusion_flutter_datagrid: ^27.2.2
  lottie: ^3.1.3
  popover: ^0.3.1
  url_launcher: ^6.3.1
  flutter_widget_from_html: ^0.15.3
  sentry_flutter: ^8.10.1
  window_manager: ^0.4.3
  htmltopdfwidgets: ^1.0.5
  internet_connection_checker_plus: ^2.7.0
  http: ^1.2.2
  shorebird_code_push: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  retrofit_generator: ^8.2.0
  flutter_launcher_icons: ^0.13.1
  isar_generator: ^3.1.0+1
```

**Comment by bryanoltman** [comment]
Thanks! I'll update this bug when I've had a chance to try this.

**Comment by bryanoltman** [comment]
I'm able to reproduce by releasing on my windows 10 laptop and patching on my windows 11 desktop. Digging in further now...

**Comment by bryanoltman** [comment]
For now, if you want to get around this, you can add `--allow-native-diffs` to your patch command and continue. As long as no plugins were updated, this should be safe. Working on a fix now.

**Comment by bryanoltman** [comment]
This has been fixed in Shorebird 1.6.6. We can't reliably detect native changes on Windows it seems, as builds made by different toolchains produce radically different .dll and .exe files :(

**Comment by Bahrom2101** [comment]
so, does this command work in ci?
```
- name: 🚀 Shorebird Patch
   uses: shorebirdtech/shorebird-patch@v0
     with:
       platform: windows
```
