### ISSUE TITLE
Re-write proxy server to use per-revision config

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#285]
We could delete the central config for the proxy server and instead make it per-revision config.

This would just mean we upload download.shorebird.dev/$revision/engine.version or similar that gives us an id that we're mapping back to.

The proxy server would then cache these mappings in memory.

**Comment by eseidel** [comment]
Proposal:
```dart
// Keeps a (fixed size) LRU cache of recently requested shorebird versions.
// First time it sees a new engine version it makes a request to storage
// for $shorebird/manifest.yaml.
// If that fails, it records and entry in the cache noting that's an invalid
// version.
// If it succeeds it records the version in the cache and returns it.
```

manifest.yaml:
```yaml
shorebird_engine_revision: e6a2a5a43973430d9f038cd81cb1779b6b404909
flutter_engine_revision: ec975089acb540fc60752606a3d3ba809dd1528b
artifact_overrides:
  # artifacts.zip
  - flutter_infra_release/flutter/$engine/android-arm-64-release/artifacts.zip
  - flutter_infra_release/flutter/$engine/android-arm-release/artifacts.zip
  - flutter_infra_release/flutter/$engine/android-x64-release/artifacts.zip
  # embedding release
  - download.flutter.io/io/flutter/flutter_embedding_release/1.0.0-$engine/flutter_embedding_release-1.0.0-$engine.pom
  - download.flutter.io/io/flutter/flutter_embedding_release/1.0.0-$engine/flutter_embedding_release-1.0.0-$engine.jar
  # arm64_v8a release
  - download.flutter.io/io/flutter/arm64_v8a_release/1.0.0-$engine/arm64_v8a_release-1.0.0-$engine.pom
  - download.flutter.io/io/flutter/arm64_v8a_release/1.0.0-$engine/arm64_v8a_release-1.0.0-$engine.jar
  # armeabi_v7a release
  - download.flutter.io/io/flutter/armeabi_v7a_release/1.0.0-$engine/armeabi_v7a_release-1.0.0-$engine.pom
  - download.flutter.io/io/flutter/armeabi_v7a_release/1.0.0-$engine/armeabi_v7a_release-1.0.0-$engine.jar
  # x86_64 release
  - download.flutter.io/io/flutter/x86_64_release/1.0.0-$engine/x86_64_release-1.0.0-$engine.pom
  - download.flutter.io/io/flutter/x86_64_release/1.0.0-$engine/x86_64_release-1.0.0-$engine.jar
```

Thoughts?
