### ISSUE TITLE
feat: CURL(REST API) for getting last app version

### ISSUE THREAD

**Issue by abikko** [shorebirdtech/shorebird#2901]
**Description**

Hello! I have an app that we using shorebird as codepush system. 

And I wanna to create an CI/CD Job, that checks does the pubspec.yaml app version exist in shorebird console

Because sometimes in work we have to bump app version manually(mirror problem, we have after Merge Request merged CI/CD Job commits bumping app version)

**Requirements**

- [ ] Create REST API to get app version

**Additional Context**

Add any other context or screenshots about the feature request go here.

**Comment by felangel** [comment]
We have an API for this and our Dart API Client is open source. It sounds like `getReleases` is what you're looking for: https://github.com/shorebirdtech/shorebird/blob/5be792c337afc7f2a8e5bc0b8874e31cdbc0efe0/packages/shorebird_code_push_client/lib/src/code_push_client.dart#L396C25-L396C36

Hope that helps 👍

**Comment by abikko** [comment]
Hello!

Sorry for responding long time,

Can you please update example? How I should sign in throw this client?

Update:

Also I tried to export SHOREBIRD_TOKEN=${SHOREBIRD_TKN} into ~.bashprofile as default,

and when I am trying to run this code:

```
dart
import 'dart:io';

import 'package:args/args.dart';
import 'package:shorebird_code_push_client/shorebird_code_push_client.dart';

void main(List<String> arguments) async {
  exitCode = 0;
  final appId = parseAppIdArgument(arguments);
  Map<String, String> env = Platform.environment;
  final token = env['SHOREBIRD_TOKEN'];
  print(token);
  final CodePushClient codePushClient = CodePushClient();
  final user = await codePushClient.getCurrentUser();
  print(user);
  final releases = await codePushClient.getReleases(appId: 'MASK');
  print(releases);
}

String parseAppIdArgument(List<String> arguments) {
  final parser = ArgParser()..addOption('appid', abbr: 'n');

  ArgResults argResults = parser.parse(arguments);

  return argResults.option('appid') ?? '';
}
```

I got this output:
```
***MASKED SHOREBIRD_TOKEN***
null
Unhandled exception:
Unauthorized. Ensure you are authenticated and try again.
#0      CodePushClient.getReleases (package:shorebird_code_push_client/src/code_push_client.dart:418:7)
<asynchronous suspension>
```

**Comment by felangel** [comment]
@abikko unfortunately our code_push_client isn't optimized for external use at the moment but the following should work if you have a `SHOREBIRD_TOKEN` in your environment:

**main.dart**
```dart
import 'package:http/http.dart' as http;
import 'package:scoped_deps/scoped_deps.dart';
import 'package:shorebird_code_push_client/shorebird_code_push_client.dart';

import 'package:shorebird_cli/src/auth/auth.dart';
import 'package:shorebird_cli/src/logging/logging.dart';
import 'package:shorebird_cli/src/shorebird_env.dart';

Future<void> main() async {
  final auth = runScoped(
    () => Auth(httpClient: http.Client()),
    values: {loggerRef, shorebirdEnvRef},
  );
  final client = CodePushClient(httpClient: auth.client);
  final releases = await client.getReleases(
    appId: '<APP_ID>',
  );
  for (final release in releases) {
    print(release.version);
  }
  auth.close();
  client.close();
}
```

**pubspec.yaml**
```yaml
name: example
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  http: ^1.0.0
  scoped_deps: ^0.1.0
  shorebird_code_push_client:
    git:
      url: https://github.com/shorebirdtech/shorebird
      path: packages/shorebird_code_push_client
      ref: stable
  shorebird_cli:
    git:
      url: https://github.com/shorebirdtech/shorebird
      path: packages/shorebird_cli
      ref: stable
```

We can't guarantee that this will continue to work in the future so please keep that in mind.

Hope that helps 👍
