### ISSUE TITLE
Shorebird Patch for Android failing on codemagic

### ISSUE THREAD

**Issue by awaisjamil-mp** [shorebirdtech/shorebird#3178]
`== Building for Android ==

> /Users/builder/.shorebird/bin/shorebird patch android --release-version 1.0.0-stg+640 --flavor stg -t lib/main_staging.dart --build-name=1.0.0 --build-number=5
⠋ Downloading patch......
✓ Downloading patch... (0.1s)
⠋ Extracting patch......
✓ Extracting patch... (0.2s)
⠋ Downloading bundletool.jar......
✓ Downloading bundletool.jar... (0.6s)
⠋ Extracting bundletool.jar......
✓ Extracting bundletool.jar... (0.9s)
⠋ Downloading aot-tools.dill......
✓ Downloading aot-tools.dill... (80ms)
⠋ Extracting aot-tools.dill......
✓ Extracting aot-tools.dill... (0.4s)
⠋ Fetching apps...
✓ Fetching apps (1.5s)
⠋ Fetching releases...
✓ Fetching releases (0.1s)
⠋ Installing Flutter 3.29.2 (b14323b05f)...
✓ Installing Flutter 3.29.2 (b14323b05f) (13.1s)
⠋ Running flutter precache...
✓ Running flutter precache (53.2s)
⠋ Fetching aab artifact...
✓ Fetching aab artifact (0.2s)
⠋ Downloading aab...
⠙ Downloading aab (0%)... (0.2s)
⠹ Downloading aab (12%)... (0.5s)
⠸ Downloading aab (17%)... (0.7s)
⠼ Downloading aab (33%)... (1.0s)
⠴ Downloading aab (51%)... (1.2s)
⠦ Downloading aab (68%)... (1.5s)
⠧ Downloading aab (86%)... (1.8s)
✓ Downloading aab (100%) (1.9s)
⠋ Downloading aot-tools.dill......
✓ Downloading aot-tools.dill... (0.2s)
⠋ Extracting aot-tools.dill......
✓ Extracting aot-tools.dill... (0.4s)
Building patch with Flutter 3.29.2 (b14323b05f)

Downloading Darwin arm64 Dart SDK from Flutter engine 82e21760c682fccf052b0329ebfd34efa7eeff68...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0  130M    0  139k    0     0   395k      0  0:05:37 --:--:--  0:05:37  395k
 43  130M   43 56.0M    0     0  38.3M      0  0:00:03  0:00:01  0:00:02 50.4M
 87  130M   87  113M    0     0  48.4M      0  0:00:02  0:00:02 --:--:-- 56.9M
100  130M  100  130M    0     0  50.3M      0  0:00:02  0:00:02 --:--:-- 58.3M
Building flutter tool...
Resolving dependencies...
Downloading packages...
+ _fe_analyzer_shared 76.0.0 (82.0.0 available)
+ _macros 0.3.3 from sdk dart
+ analyzer 6.11.0 (7.4.5 available)
+ archive 3.6.1 (4.0.7 available)
+ args 2.6.0 (2.7.0 available)
+ async 2.12.0 (2.13.0 available)
+ boolean_selector 2.1.2
+ browser_launcher 1.1.3
+ built_collection 5.1.1
+ built_value 8.9.3 (8.10.1 available)
+ checked_yaml 2.0.3 (2.0.4 available)
+ clock 1.1.2
+ collection 1.19.1
+ completion 1.0.1
+ convert 3.1.2
+ coverage 1.11.1 (1.14.1 available)
+ crypto 3.0.6
+ csslib 1.0.2
+ dap 1.4.0
+ dds 5.0.0 (5.0.3 available)
+ dds_service_extensions 2.0.1 (2.0.2 available)
+ devtools_shared 11.2.0 (12.0.0 available)
+ dtd 2.4.0 (4.0.0 available)
+ dwds 24.3.2 (24.3.11 available)
+ extension_discovery 2.1.0
+ fake_async 1.3.2 (1.3.3 available)
+ ffi 2.1.3 (2.1.4 available)
+ file 7.0.1
+ file_testing 3.0.2
+ fixnum 1.1.1
+ flutter_template_images 5.0.0
+ frontend_server_client 4.0.0
+ glob 2.1.2 (2.1.3 available)
+ graphs 2.3.2
+ html 0.15.5 (0.15.6 available)
+ http 1.2.2 (1.4.0 available)
+ http_multi_server 3.2.2
+ http_parser 4.1.2
+ intl 0.19.0 (0.20.2 available)
+ io 1.0.5
+ js 0.7.1 (discontinued)
+ json_annotation 4.9.0
+ json_rpc_2 3.0.3 (4.0.0 available)
+ logging 1.3.0
+ macros 0.1.3-main.0
+ matcher 0.12.17
+ meta 1.16.0 (1.17.0 available)
+ mime 2.0.0
+ multicast_dns 0.3.2+7 (0.3.3 available)
+ mustache_template 2.0.0
+ native_assets_builder 0.10.2 (discontinued replaced by hooks_runner)
+ native_assets_cli 0.10.0 (discontinued replaced by hooks)
+ native_stack_traces 0.6.0 (0.6.1 available)
+ node_preamble 2.0.2
+ package_config 2.1.1 (2.2.0 available)
+ path 1.9.1
+ petitparser 6.1.0 (7.0.0 available)
+ platform 3.1.6
+ pool 1.5.1
+ process 5.0.3 (5.0.4 available)
+ pub_semver 2.1.5 (2.2.0 available)
+ pubspec_parse 1.5.0
+ shelf 1.4.2
+ shelf_packages_handler 3.0.2
+ shelf_proxy 1.0.4
+ shelf_static 1.1.3
+ shelf_web_socket 2.0.1 (3.0.0 available)
+ source_map_stack_trace 2.1.2
+ source_maps 0.10.13
+ source_span 1.10.1
+ sprintf 7.0.0
+ sse 4.1.7 (4.1.8 available)
+ stack_trace 1.12.1
+ standard_message_codec 0.0.1+4
+ stream_channel 2.1.4
+ string_scanner 1.4.1
+ sync_http 0.3.1
+ term_glyph 1.2.2
+ test 1.25.14 (1.26.2 available)
+ test_api 0.7.4 (0.7.6 available)
+ test_core 0.6.8 (0.6.11 available)
+ typed_data 1.4.0
+ unified_analytics 7.0.1 (8.0.1 available)
+ usage 4.1.1 (discontinued)
+ uuid 4.5.1
+ vm_service 14.3.1 (15.0.2 available)
+ vm_service_interface 2.0.1
+ vm_snapshot_analysis 0.7.6
+ watcher 1.1.1 (1.1.2 available)
+ web 1.1.0 (1.1.1 available)
+ web_socket 0.1.6 (1.0.1 available)
+ web_socket_channel 3.0.1 (3.0.3 available)
+ webdriver 3.0.4 (3.1.0 available)
+ webkit_inspection_protocol 1.2.1
+ xml 6.5.0 (6.6.0 available)
+ yaml 3.1.3
+ yaml_edit 2.2.2
Changed 97 dependencies!
4 packages are discontinued.
43 packages have newer versions incompatible with dependency constraints.
Try `dart pub outdated` for more information.
Downloading Material fonts...                                      303ms
Downloading Gradle Wrapper...                                       83ms
Downloading package sky_engine...                                  185ms
Downloading package flutter_gpu...                                 125ms
Downloading flutter_patched_sdk tools...                           205ms
Downloading flutter_patched_sdk_product tools...                   229ms
Downloading darwin-arm64 tools...                                1,285ms
Downloading libimobiledevice...                                    110ms
Downloading usbmuxd...                                              81ms
Downloading libplist...                                             80ms
Downloading openssl...                                             109ms
Downloading ios-deploy...                                           84ms
Downloading darwin-arm64/font-subset tools...                      162ms
Downloading android-arm-profile/darwin-x64 tools...                188ms
Downloading android-arm-release/darwin-x64 tools...                180ms
Downloading android-arm64-profile/darwin-x64 tools...              198ms
Downloading android-arm64-release/darwin-x64 tools...              206ms
Downloading android-x64-profile/darwin-x64 tools...                188ms
Downloading android-x64-release/darwin-x64 tools...                197ms
Resolving dependencies...
Downloading packages...
  archive 3.6.1 (4.0.7 available)
  async 2.12.0 (2.13.0 available)
  checked_yaml 2.0.3 (2.0.4 available)
  dcli 6.0.5 (7.0.5 available)
  dcli_common 6.1.2 (7.0.2 available)
  dcli_core 6.1.2 (7.0.3 available)
  dcli_terminal 6.1.2 (7.0.3 available)
  dd_check_plugin 3.1.7 (4.0.1 available)
  dotted_border 2.1.0 (3.0.1 available)
  facebook_app_events 0.19.7 (0.20.1 available)
  fake_async 1.3.2 (1.3.3 available)
  flutter_launcher_icons 0.13.1 (0.14.4 available)
  flutter_lints 5.0.0 (6.0.0 available)
  flutter_local_notifications 17.2.4 (19.2.1 available)
  flutter_local_notifications_linux 4.0.1 (6.0.0 available)
  flutter_local_notifications_platform_interface 7.2.0 (9.0.0 available)
  flutter_native_splash 2.4.4 (2.4.6 available)
  flutter_stripe 10.2.0 (11.5.0 available)
  freezed 2.5.8 (3.0.6 available)
  freezed_annotation 2.4.4 (3.0.0 available)
  geocoding 3.0.0 (4.0.0 available)
  geocoding_android 3.3.1 (4.0.1 available)
  get_it 7.7.0 (8.0.3 available)
  health 12.2.1 (13.1.0 available)
  image 4.3.0 (4.5.4 available)
  intl 0.19.0 (0.20.2 available)
  leak_tracker 10.0.8 (11.0.1 available)
  leak_tracker_flutter_testing 3.0.9 (3.0.10 available)
  leak_tracker_testing 3.0.1 (3.0.2 available)
  lints 5.1.1 (6.0.0 available)
  lottie 3.3.0 (3.3.1 available)
  material_color_utilities 0.11.1 (0.13.0 available)
  meta 1.16.0 (1.17.0 available)
  mime 1.0.6 (2.0.0 available)
  native_synchronization_temp 0.6.0 (0.7.1 available)
  network_info_plus 5.0.3 (6.1.4 available)
  package_info_plus 6.0.0 (8.3.0 available)
  package_info_plus_platform_interface 2.0.1 (3.2.0 available)
  permission_handler 11.4.0 (12.0.0+1 available)
  permission_handler_android 12.1.0 (13.0.1 available)
  petitparser 6.1.0 (7.0.0 available)
  rxdart 0.27.7 (0.28.0 available)
  share_plus 9.0.0 (11.0.0 available)
  share_plus_platform_interface 4.0.0 (6.0.0 available)
  sign_in_with_apple 6.1.4 (7.0.1 available)
  sign_in_with_apple_platform_interface 1.1.0 (2.0.0 available)
  sign_in_with_apple_web 2.1.1 (3.0.0 available)
! stack_trace 1.12.0 (overridden) (1.12.1 available)
  strings 3.1.2 (4.0.0 available)
  stripe_android 10.2.1 (11.5.0 available)
  stripe_ios 10.2.0 (11.5.0 available)
  stripe_platform_interface 10.2.0 (11.5.0 available)
  sum_types 0.3.5 (0.4.0 available)
  test 1.25.15 (1.26.2 available)
  test_api 0.7.4 (0.7.6 available)
  test_core 0.6.8 (0.6.11 available)
  timezone 0.9.4 (0.10.1 available)
  unicode 0.3.1 (1.1.8 available)
  vector_math 2.1.4 (2.2.0 available)
  vm_service 14.3.1 (15.0.2 available)
! web 1.1.1 (overridden)
  win32 5.13.0 (5.14.0 available)
  xml 6.5.0 (6.6.0 available)
Got dependencies!
62 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

Running Gradle task 'bundleStgRelease'...                       
Picked up JAVA_TOOL_OPTIONS: -Xmx5g
Picked up JAVA_TOOL_OPTIONS: -Xmx5g
Checking the license for package NDK (Side by side) 27.0.12077973 in /usr/local/share/android-sdk/licenses
License for package NDK (Side by side) 27.0.12077973 accepted.
Preparing "Install NDK (Side by side) 27.0.12077973 v.27.0.12077973".
"Install NDK (Side by side) 27.0.12077973 v.27.0.12077973" ready.
Installing NDK (Side by side) 27.0.12077973 in /usr/local/share/android-sdk/ndk/27.0.12077973
"Install NDK (Side by side) 27.0.12077973 v.27.0.12077973" complete.
"Install NDK (Side by side) 27.0.12077973 v.27.0.12077973" finished.
Checking the license for package Android SDK Build-Tools 35 in /usr/local/share/android-sdk/licenses
License for package Android SDK Build-Tools 35 accepted.
Preparing "Install Android SDK Build-Tools 35 v.35.0.0".
"Install Android SDK Build-Tools 35 v.35.0.0" ready.
Installing Android SDK Build-Tools 35 in /usr/local/share/android-sdk/build-tools/35.0.0
"Install Android SDK Build-Tools 35 v.35.0.0" complete.
"Install Android SDK Build-Tools 35 v.35.0.0" finished.
Checking the license for package Android SDK Platform 34 in /usr/local/share/android-sdk/licenses
License for package Android SDK Platform 34 accepted.
Preparing "Install Android SDK Platform 34 (revision 3)".
"Install Android SDK Platform 34 (revision 3)" ready.
Installing Android SDK Platform 34 in /usr/local/share/android-sdk/platforms/android-34
"Install Android SDK Platform 34 (revision 3)" complete.
"Install Android SDK Platform 34 (revision 3)" finished.
Expected to find fonts for (MaterialIcons, packages/cupertino_icons/CupertinoIcons), but found (MaterialIcons). This usually means you are referring to font families in an IconData class but not including them in the assets section of your pubspec.yaml, are missing the package that would include them, or are missing "uses-material-design: true".
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 6528 bytes (99.6% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Picked up JAVA_TOOL_OPTIONS: -Xmx5g

Picked up JAVA_TOOL_OPTIONS: -Xmx5g

Picked up JAVA_TOOL_OPTIONS: -Xmx5g

Expected to find fonts for (MaterialIcons, packages/cupertino_icons/CupertinoIcons), but found (MaterialIcons). This usually means you are referring to font families in an IconData class but not including them in the assets section of your pubspec.yaml, are missing the package that would include them, or are missing "uses-material-design: true".
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 6528 bytes (99.6% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Running Gradle task 'bundleStgRelease'...                        1724.8s
✓ Built build/app/outputs/bundle/stgRelease/app-stg-release.aab (89.3MB)
⠋ Verifying patch can be applied to release...
✓ Verifying patch can be applied to release (92ms)
[WARN] Your app contains native changes, which cannot be applied with a patch.
    Changed files:
        base/dex/classes8.dex

If you don't know why you're seeing this error, visit our troubleshooting page at https://docs.shorebird.dev/faq
Instance of 'UnpatchableChangeException'

If you aren't sure why this command failed, re-run with the --verbose flag to see more information.

You can also [file an issue](https://github.com/shorebirdtech/shorebird/issues/new/choose) if you think this is a bug. Please include the following log file in your report:
/Users/builder/Library/Application Support/shorebird/logs/1750151564508_shorebird.log

Build failed :|
Failed to build for Android
`

there is not native change only flutter side change

**Comment by bryanoltman** [comment]
Changes to the .dex file represent native changes. If you don't know where these came from, the culprit is almost always a plugin (i.e., a package that interacts with the underlying native platform) was updated unintentionally. Are you tracking your `pubspec.lock` file in source control?

**Comment by awaisjamil-mp** [comment]
no i am not tracking pubspec.lock file in source control. but i am confused why its working for ios

**Comment by awaisjamil-mp** [comment]
i just tracked pubspec.lock to git and tried again it still failed with same message. i am stuck here for 3 days now

**Comment by bryanoltman** [comment]
> i just tracked pubspec.lock to git and tried again it still failed with same message. i am stuck here for 3 days now

If you just started tracking it, you will continue to run into this issue until you create a new release.

Also, I feel like I should mention that the reason we recommend tracking the file is so you can identify changes when they occur and only change plugin dependency versions when you're ready (i.e., with a new release)

>  i am confused why its working for ios

Most likely, the plugin that was updated did not include any iOS changes in the new version.

**Comment by awaisjamil-mp** [comment]
after tracking pubspec.lock i have create 3 new releases and still patching fails on android.

**Comment by bryanoltman** [comment]
If you create a release and then immediately patch with no changes, do you see this issue?

**Comment by awaisjamil-mp** [comment]
yes, thats exactly what i am doing.

**Comment by awaisjamil-mp** [comment]
```
name: mobile
description: Meal Planet Mobile App.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.1+99
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_alice: 2.0.1
  fluttertoast: 8.2.12
  google_sign_in: 6.3.0
  firebase_core: 3.14.0
  firebase_performance: 0.10.1+7
  firebase_performance_dio: 0.7.1
  flutter_launcher_icons: 0.14.4
  flutter_svg: 2.2.0
  cached_network_image: 3.4.1
  flutter_bloc: 9.1.1
  go_router: 15.2.0
  kiwi: 5.0.1
  dio: 5.8.0+1
  retrofit: 4.4.2
  firebase_analytics: 11.5.0
  firebase_crashlytics: 4.3.7
  firebase_messaging: 15.2.7
  get_storage: 2.1.1
  flutter_easyloading: 3.0.5
  geolocator: 14.0.1
  shimmer: 3.0.0
  dotted_border: 3.0.1
  google_maps_flutter: 2.12.3
  geocoding: 4.0.0
  permission_handler: 12.0.0+1
  flutter_rating_stars: 1.1.0
  onesignal_flutter: 5.3.3
  flutter_stripe: 11.5.0
  facebook_app_events: 0.20.1
  bloc_test: 10.0.0
  flutter_rating_bar: 4.0.1
  lottie: 3.3.0
  instabug_flutter: 14.3.1
  email_validator: 3.0.0
  url_launcher: 6.3.1
  pinput: 5.0.1
  flutter_native_splash: 2.4.4
  sign_in_with_apple: 7.0.1
  webview_flutter: 4.13.0
  firebase_remote_config: 5.4.5
  datadog_flutter_plugin: 2.11.0
  datadog_tracking_http_client: 2.3.0
  appsflyer_sdk: 6.16.2
  freshchat_sdk: 0.10.25
  flutter_cache_manager: 3.4.1
  flutter_local_notifications: 19.2.1
  cloud_functions: 5.5.2
  connectivity_plus: 6.1.4
  flutter_uxcam: 2.6.1
  phrase: 2.5.2
  rxdart: 0.28.0
  freezed: 2.5.8
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  equatable: 2.0.7
  collection: 1.19.1
  intl: 0.19.0
  provider: 6.1.5
  flutter_slidable: 4.0.0
  keyboard_actions: 4.2.0
  share_plus: 11.0.0
  syncfusion_flutter_charts: 29.2.11
  tutorial_coach_mark: 1.3.0
  app_tracking_transparency: 2.0.6+1
  package_info_plus: 8.3.0
  segment_analytics: 1.1.7
  video_player: 2.10.0
  adjust_sdk: 5.4.0
  app_links: 6.4.0
  flutter_dotenv: 5.2.1
  ntp: 2.0.0
  pluralize: 0.0.8
  calendar_date_picker2: 2.0.1
  dartz: 0.10.1
  carousel_slider: 5.1.1
  clipboard: 0.1.3
  uuid: 4.5.1
  design_system:
    path: packages/design_system

  support:
    path: packages/support

  analytics_service:
    path: packages/analytics_service

  checkout_flutter:
    path: plugins/checkout_flutter
  mp_logger:
    path: packages/mp_logger
  cloud_firestore: 5.6.9
  showcaseview: 4.0.1
  health: 13.1.0
  animations: 2.0.11
  tiktok_events_sdk: 1.0.9
  shorebird_code_push: 2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  arb_utils: 0.8.3
  flutter_lints: 5.0.0
  json_serializable: 6.9.5
  build_runner: 2.5.2
  retrofit_generator: 9.2.0
  mocktail: 1.0.4
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  http: 1.2.2
  uuid: 4.5.1

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/
    - assets/jsonstubs/
    - assets/app_icons/
    - env/.env.stg
    - env/.env.dev
    - env/.env.prod
    - shorebird.yaml

flutter_native_splash:
  color: "#E9EFE9"
  image: assets/app_icons/splash_native_loader.png
  color_dark: "#E9EFE9"
  android_gravity: center_vertical
  ios_content_mode: center
  fullscreen: true

  android_12:
    color: "#E9EFE9"
    image: assets/app_icons/splash_native_loader.png
    icon_background_color: "#E9EFE9"
    image_dark: assets/app_icons/splash_native_loader.png
    icon_background_color_dark: "#E9EFE9"
    fullscreen: true

  web: false

flutter_launcher_icons:
  image_path: "assets/app_icons/splash_native_loader.png"
  android: false
  ios: true
  remove_alpha_ios: true
```

here is my pubspec.yaml and below is build.gradle
```
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'com.google.gms.google-services'
    id 'dev.flutter.flutter-gradle-plugin'

    alias(libs.plugins.compose.compiler) apply false
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

android {
    namespace "com.mealplanet.mobile"
    compileSdkVersion 35
    ndkVersion = "27.0.12077973"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
        coreLibraryDesugaringEnabled true
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/kotlin'
    }

    defaultConfig {
        applicationId "com.mealplanet.mobile"
        minSdkVersion 26
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
        ndk.abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
    }

    lintOptions {
        checkReleaseBuilds false
    }

    signingConfigs {
        release {
            storeFile file('keystores/release')
            keyAlias = KEYSTORE_ALIAS
            storePassword KEYSTORE_PASSWORD
            keyPassword KEY_PASSWORD
        }
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.12"
    }

    flavorDimensions "app"
    productFlavors {
        development {
            dimension "app"
            resValue "string", "app_name", "MP-Dev"
            applicationIdSuffix ".development"
            versionNameSuffix "-development"
            manifestPlaceholders = [flavorName: "development", hostName: "mainactivity", scheme: "mealplanetmobileappdev"]
        }
        stg {
            dimension "app"
            resValue "string", "app_name", "MP-Stg"
            applicationIdSuffix ".stg"
            versionNameSuffix "-stg"
            manifestPlaceholders = [flavorName: "stg", hostName: "mainactivity", scheme: "mealplanetmobileappstg"]
        }
        prod {
            dimension "app"
            applicationId "com.mealplanet.mobile"
            resValue "string", "app_name", "MealPlanet"
            manifestPlaceholders = [flavorName: "prod", hostName: "mainactivity", scheme: "mealplanetmobileapp"]
        }
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            versionNameSuffix '-debug'
            matchingFallbacks = ['debug']
        }
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            shrinkResources false
            ndk {
                abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86_64'
            }
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation(platform("com.google.firebase:firebase-bom:32.2.0"))
    implementation("com.google.firebase:firebase-messaging")

    implementation("com.google.firebase:firebase-analytics-ktx")
    implementation("com.google.android.gms:play-services-auth:19.2.0")

    implementation(platform("com.squareup.okhttp3:okhttp-bom:4.12.0"))
    implementation("com.squareup.okhttp3:okhttp")
    implementation("com.squareup.okhttp3:logging-interceptor")

    implementation("androidx.work:work-runtime-ktx:2.8.1")

    // for adjust sdk
    implementation 'com.google.android.gms:play-services-ads-identifier:18.1.0'
    implementation 'com.adjust.sdk:adjust-android:5.1.0'
    implementation 'com.android.installreferrer:installreferrer:2.2'
    implementation 'com.adjust.sdk:adjust-android-meta-referrer:5.0.1'

    // desugaring required some libs like flutter_local_notifications
    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:2.1.4"
}

```
