### ISSUE TITLE
fix: flavours are not being detected.

### ISSUE THREAD

**Issue by RemeJuan** [shorebirdtech/shorebird#718]
**Description**

Just began the setup and it was completed, however, none of the app flavours was detected, of which there are 8.
I tried running init again with `--force` with no change.

These flavors have existed for quite some time and we build with them using the normal flutter build commands.

**Steps To Reproduce**

1. run `shorebird init`
2. No errors shown, yaml file generated.

**Expected Behavior**

Expect the flavours to have been detected

**Additional Context**

```
`android/app/build.gradle`:


android {
    // ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
    flavorDimensions "flavor-type"

    productFlavors {
        l_journey {
            dimension "flavor-type"
            applicationId "REDACTED"
            resValue "string", "app_name", "REDACTED - Journey"
        }
        l_dev {
            dimension "flavor-type"
            applicationId "REDACTED"
            resValue "string", "app_name", "REDACTED - Dev"
        }
        l_uat {
            dimension "flavor-type"
            applicationId "REDACTED"
            resValue "string", "app_name", "REDACTED - UAT"
        }
        l_prod {
            dimension "flavor-type"
            applicationId "REDACTED"
            resValue "string", "app_name", "REDACTED"
        }
        o_journey {
            dimension "flavor-type"
            applicationId "REDACTED"
            resValue "string", "app_name", "REDACTED - Journey"
        }
        o_dev {
            dimension "flavor-type"
            applicationId "REDACTED"
            resValue "string", "app_name", "REDACTED - Dev"
        }
        o_uat {
            dimension "flavor-type"
            applicationId "REDACTED"
            resValue "string", "app_name", "REDACTED - UAT"
        }
        o_prod {
            dimension "flavor-type"
            applicationId "REDACTED"
            resValue "string", "app_name", "REDACTED"
        }
    }

    // ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----
}
```

**Comment by felangel** [comment]
Hi @RemeJuan 👋
Thanks for opening an issue! Can you specify the version of shorebird you are currently using? I’ll take a look shortly and see if I’m able to reproduce. Sorry for the inconvenience!

**Comment by RemeJuan** [comment]
@felangel no worries, I have plenty of time to set this up, just really happy it exists.
Would also imagine 8 flavors are not common.

```
Shorebird 0.6.0
Shorebird Engine • revision 6c1f35b941ba46596b88674cbb7c59ac3eff1119
```

Thanks

**Comment by felangel** [comment]
@RemeJuan I tried to reproduce and was unable. I ran `shorebird init` with following `app/build.gradle` file:

```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    namespace "com.example.multiple_deployments"
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.multiple_deployments"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    flavorDimensions "flavor-type"
    productFlavors {
        l_journey {
            dimension "flavor-type"
            manifestPlaceholders = [applicationLabel: "Shorebird Example"]
        }
        l_dev {
            dimension "flavor-type"
            manifestPlaceholders = [applicationLabel: "Shorebird Example"]
        }
        l_uat {
            dimension "flavor-type"
            manifestPlaceholders = [applicationLabel: "Shorebird Example"]
        }
        l_prod {
            dimension "flavor-type"
            manifestPlaceholders = [applicationLabel: "Shorebird Example"]
        }
        o_journey {
            dimension "flavor-type"
            manifestPlaceholders = [applicationLabel: "Shorebird Example"]
        }
        o_dev {
            dimension "flavor-type"
            manifestPlaceholders = [applicationLabel: "Shorebird Example"]
        }
        o_uat {
            dimension "flavor-type"
            manifestPlaceholders = [applicationLabel: "Shorebird Example"]
        }
        o_prod {
            dimension "flavor-type"
            manifestPlaceholders = [applicationLabel: "Shorebird Example"]
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

And the generated `shorebird.yaml` was:

```yaml
# This file is used to configure the Shorebird updater used by your application.
# Learn more at https://shorebird.dev
# This file should be checked into version control.

# This is the unique identifier assigned to your app.
# It is used by your app to request the correct patches from Shorebird servers.
app_id: c92c0dd1-c273-46c6-8d74-1066ca10265f
flavors:
  l_dev: c92c0dd1-c273-46c6-8d74-1066ca10265f
  l_journey: cf782a9a-b33b-4fc4-8652-7a262cba583f
  l_prod: 49f57f32-a773-4fc2-9c9d-5d5245f634a8
  l_uat: b7322272-1854-4d57-a798-8aa5d43b32ae
  o_dev: a780f98c-e870-4ba5-8ee6-12631ad15230
  o_journey: 78e06b90-f6a6-479c-85d5-c2cc5e3ea0a5
  o_prod: 5bb9a326-b3a7-4afe-972b-06ca749b7617
  o_uat: f4ac189d-513a-492b-9048-fa7e0897c9ba
```

Can you describe in a bit more detail what you're seeing? If you could share a link to a minimal reproduction sample that would also be great, thanks!
